defaults: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: gallery_appointments_dev
  margin-top: 9pxe
  pool: 5
  username: zazou
  password: 
  
test:
  adapter: postgresql
  encoding: unicode
  database: gallery_appointments_test
  pool: 5
  username: zazou
  password: 
